version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: sub_db
    environment:
      POSTGRES_DB: subscription_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sub_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: subscription_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/subscription_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SERVER_PORT: 8086
    ports:
      - "8086:8086"
    restart: unless-stopped

volumes:
  pgdata:
